drop table if exists provincias;
create table provincias(
id integer unsigned primary key,
id_departamento integer unsigned not null,
provincia varchar(50)not null
);
insert into provincia values ('0', '0', 'DESCONOCIDO');
insert into provincia values ('1', '1', 'Cercado');
insert into provincia values ('2', '1', 'Gral. J. Ballivian');
insert into provincia values ('3', '1', 'Iténez');
insert into provincia values ('4', '1', 'Mamore');
insert into provincia values ('5', '1', 'Marban');
insert into provincia values ('6', '1', 'Moxos');
insert into provincia values ('7', '1', 'Vaca Diez');
insert into provincia values ('8', '1', 'Yacuma');
insert into provincia values ('9', '2', 'Azurduy');
insert into provincia values ('10', '2', 'B. Boeto');
insert into provincia values ('11', '2', 'Hernando Siles');
insert into provincia values ('12', '2', 'Luis Calvo');
insert into provincia values ('13', '2', 'Nor Cinti');
insert into provincia values ('14', '2', 'Oropeza');
insert into provincia values ('15', '2', 'Sud Cinti');
insert into provincia values ('16', '2', 'Tomina');
insert into provincia values ('17', '2', 'Yamparaez');
insert into provincia values ('18', '2', 'Zudañez');
insert into provincia values ('19', '3', 'Arani');
insert into provincia values ('20', '3', 'Arque');
insert into provincia values ('21', '3', 'Ayopaya');
insert into provincia values ('22', '3', 'Bolivar');
insert into provincia values ('23', '3', 'Campero');
insert into provincia values ('24', '3', 'Capinota');
insert into provincia values ('25', '3', 'Carrasco');
insert into provincia values ('26', '3', 'Cercado');
insert into provincia values ('27', '3', 'Chapare');
insert into provincia values ('28', '3', 'Esteban Arze');
insert into provincia values ('29', '3', 'German Jordan');
insert into provincia values ('30', '3', 'Mizque');
insert into provincia values ('31', '3', 'Punata');
insert into provincia values ('32', '3', 'Quillacollo');
insert into provincia values ('33', '3', 'Tapacari');
insert into provincia values ('34', '3', 'Tiraque');
insert into provincia values ('35', '4', 'Aroma');
insert into provincia values ('36', '4', 'Bautista Saavedra');
insert into provincia values ('37', '4', 'Camacho');
insert into provincia values ('38', '4', 'Caranavi');
insert into provincia values ('39', '4', 'Franz Tamayo');
insert into provincia values ('40', '4', 'Gral. Jose Manuel Pando');
insert into provincia values ('41', '4', 'Gualberto Villarroel');
insert into provincia values ('42', '4', 'Ingavi');
insert into provincia values ('43', '4', 'Inquisivi');
insert into provincia values ('44', '4', 'Iturralde');
insert into provincia values ('45', '4', 'Larecaja');
insert into provincia values ('46', '4', 'Loayza');
insert into provincia values ('47', '4', 'Los Andes');
insert into provincia values ('48', '4', 'Manco Kapac');
insert into provincia values ('49', '4', 'Muñecas');
insert into provincia values ('50', '4', 'Murillo');
insert into provincia values ('51', '4', 'Nor Yungas');
insert into provincia values ('52', '4', 'Omasuyos');
insert into provincia values ('53', '4', 'Pacajes');
insert into provincia values ('54', '4', 'Sud Yungas');
insert into provincia values ('55', '5', 'Atahuallpa');
insert into provincia values ('56', '5', 'Avaroa');
insert into provincia values ('57', '5', 'Carangas');
insert into provincia values ('58', '5', 'Cercado');
insert into provincia values ('59', '5', 'Ladislao Cabrera');
insert into provincia values ('60', '5', 'Litoral');
insert into provincia values ('61', '5', 'Mejillones');
insert into provincia values ('62', '5', 'Nor Carangas');
insert into provincia values ('63', '5', 'Pantaleon Dalence');
insert into provincia values ('64', '5', 'Poopó');
insert into provincia values ('65', '5', 'Sajama');
insert into provincia values ('66', '5', 'San Pedro de Totora');
insert into provincia values ('67', '5', 'Saucari');
insert into provincia values ('68', '5', 'Sebastian Pagador');
insert into provincia values ('69', '5', 'Sud Carangas');
insert into provincia values ('70', '5', 'Tomas Barron');
insert into provincia values ('71', '6', 'Abuna');
insert into provincia values ('72', '6', 'Gral. Federico Roman');
insert into provincia values ('73', '6', 'Madre de Dios');
insert into provincia values ('74', '6', 'Manuripi');
insert into provincia values ('75', '6', 'Nicolas Suarez');
insert into provincia values ('76', '7', 'Alonzo de Ibañez');
insert into provincia values ('77', '7', 'Antonio Quijarro');
insert into provincia values ('78', '7', 'Charcas');
insert into provincia values ('79', '7', 'Chayanta');
insert into provincia values ('80', '7', 'Cornelio Saavedra');
insert into provincia values ('81', '7', 'Daniel Campos');
insert into provincia values ('82', '7', 'Enrique Baldivieso');
insert into provincia values ('83', '7', 'Gral.B.Bilbao');
insert into provincia values ('84', '7', 'Jose Maria Linares');
insert into provincia values ('85', '7', 'Modesto Omiste');
insert into provincia values ('86', '7', 'Nor Chichas');
insert into provincia values ('87', '7', 'Nor Lipez');
insert into provincia values ('88', '7', 'Rafael Bustillo');
insert into provincia values ('89', '7', 'Sud Chichas');
insert into provincia values ('90', '7', 'Sud Lipez');
insert into provincia values ('91', '7', 'Tomas Frias');
insert into provincia values ('92', '8', 'Andres Ibañez');
insert into provincia values ('93', '8', 'Angel Sandoval');
insert into provincia values ('94', '8', 'Chiquitos');
insert into provincia values ('95', '8', 'Cordillera');
insert into provincia values ('96', '8', 'Florida');
insert into provincia values ('97', '8', 'German Busch');
insert into provincia values ('98', '8', 'Guarayos');
insert into provincia values ('99', '8', 'Ichilo');
insert into provincia values ('100', '8', 'Manuel Maria Caballero');
insert into provincia values ('101', '8', 'Ñuflo de Chavez');
insert into provincia values ('102', '8', 'Obispo Santistevan');
insert into provincia values ('103', '8', 'Sara');
insert into provincia values ('104', '8', 'Vallegrande');
insert into provincia values ('105', '8', 'Velasco');
insert into provincia values ('106', '8', 'Warnes');
insert into provincia values ('107', '9', 'Arce');
insert into provincia values ('108', '9', 'Aviles');
insert into provincia values ('109', '9', 'Cercado');
insert into provincia values ('110', '9', 'Gran Chaco');
insert into provincia values ('111', '9', 'Mendez');
insert into provincia values ('112', '9', 'O''Connor');
